apiVersion: v1
data:
  SERVER_PORT: "3000"
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"kind":"ConfigMap","apiVersion":"v1","metadata":{"name":"webserver-env-file","creationTimestamp":null},"data":{"SERVER_PORT":"3000"}}
  creationTimestamp: "2020-11-26T22:49:41Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:SERVER_PORT: {}
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
    manager: kubectl
    operation: Update
    time: "2020-11-26T22:49:41Z"
  name: webserver-env-file
  namespace: default
  resourceVersion: "11772"
  selfLink: /api/v1/namespaces/default/configmaps/webserver-env-file
  uid: 42524fbd-e93b-4140-b8d8-1f3a9706eeca
