apiVersion: v1
kind: Service
metadata:
  name: webserver
  labels:
    app: webserver
spec:
  type: LoadBalancer
  selector:
    app: webserver
  ports:
    - protocol: TCP
      targetPort: 3000
      port: 80
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
  labels:
    app: webserver
spec:
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      labels:
        app: webserver
    spec:
      containers:
        - name: webserver
          image: mrjakblade30/sdtd-webserver
          ports:
            - containerPort: 3000
          envFrom:
          - configMapRef:
              name: webserver-env-file
          imagePullPolicy: Always
