build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  variables:
    MODULE_DIR: "${CI_PROJECT_DIR}/system"
    WEBSERVER_DIR: "${CI_PROJECT_DIR}/system/webserver"
    APISERVER_DIR: "${CI_PROJECT_DIR}/system/apiserver"
  script:
    - echo $MODULE_DIR
    - echo $APISERVER_DIR
    - echo $WEBSERVER_DIR
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $APISERVER_DIR --dockerfile $APISERVER_DIR/Dockerfile --destination $CI_REGISTRY_IMAGE/apiserver:$CI_COMMIT_TAG
    - /kaniko/executor --context $WEBSERVER_DIR --dockerfile $WEBSERVER_DIR/Dockerfile --destination $CI_REGISTRY_IMAGE/webserver:$CI_COMMIT_TAG
  only:
    - master
