build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - echo $CI_PROJECT_DIR
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR/system/apiserver --dockerfile $CI_PROJECT_DIR/system/apiserver/Dockerfile --destination $CI_REGISTRY_IMAGE/apiserver:$CI_COMMIT_TAG
    - /kaniko/executor --context $CI_PROJECT_DIR/system/webserver --dockerfile $CI_PROJECT_DIR/system/webserver/Dockerfile --destination $CI_REGISTRY_IMAGE/webserver:$CI_COMMIT_TAG
  only:
    - pipeline
