apiVersion: v1
kind: Secret
metadata:
  name: myregistrykey
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJnaXRsYWIuZW5zaW1hZy5mciI6IHsKCQkJImF1dGgiOiAiWTJoaGJHOTFjRzA2Wld3emNHaGhiblEzWVd4TCIKCQl9LAoJCSJnaXRsYWIuZW5zaW1hZy5mcjo1MDUwIjogewoJCQkiYXV0aCI6ICJZMmhoYkc5MWNHMDZaV3d6Y0doaGJuUTNZV3hMIgoJCX0KCX0sCgkiSHR0cEhlYWRlcnMiOiB7CgkJIlVzZXItQWdlbnQiOiAiRG9ja2VyLUNsaWVudC8xOS4wMy4xMy1jZSAobGludXgpIgoJfQp9Cg==
type: kubernetes.io/dockerconfigjson
