apiVersion: v1
kind: Service
metadata:
  name: client
  labels:
    app: client
spec:
  selector:
    app: client
  ports:
    - protocol: TCP
      targetPort: 3001
      port: 3001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  labels:
    app: client
spec:
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: gitlab.ensimag.fr:5050/sdtd1/projet-sdtd/client:latest
          ports:
            - containerPort: 3001
          imagePullPolicy: Always
      imagePullSecrets:
        - name: myregistrykey
