apiVersion: v1
data:
  DATABASE_CONNECTIONSTRING: mongodb://my-user:userPassword@db-svc.default.svc.cluster.local:27017/?replicaSet=db
  SERVER_PORT: "3001"
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"kind":"ConfigMap","apiVersion":"v1","metadata":{"name":"apiserver-env-file","creationTimestamp":null},"data":{"DATABASE_CONNECTIONSTRING":"mongodb://my-user:userPassword@db-svc:27017","SERVER_PORT":"3001"}}
  creationTimestamp: "2020-11-27T20:39:35Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:DATABASE_CONNECTIONSTRING: {}
        f:SERVER_PORT: {}
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
    manager: kubectl
    operation: Update
    time: "2020-11-27T20:39:35Z"
  name: apiserver-env-file
  namespace: default
  resourceVersion: "30940"
  selfLink: /api/v1/namespaces/default/configmaps/apiserver-env-file
  uid: 7ad675e3-8886-4f4d-b440-1ca6bf5652bd
