apiVersion: v1
kind: Service
metadata:
  name: apiserver
  labels:
    app: apiserver
spec:
  selector:
    app: apiserver
  ports:
    - protocol: TCP
      targetPort: 3001
      port: 3001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apiserver
  labels:
    app: apiserver
spec:
  selector:
    matchLabels:
      app: apiserver
  template:
    metadata:
      labels:
        app: apiserver
    spec:
      containers:
        - name: apiserver
          image: gitlab.ensimag.fr:5050/sdtd1/projet-sdtd/apiserver:latest
          ports:
            - containerPort: 3001
          envFrom:
            - configMapRef:
                name: apiserver-env-file
          #- secretRef:
          #    name: apiserver-secret-file
          livenessProbe:
            httpGet:
              path: /api/ping
              port: 3001
            initialDelaySeconds: 60
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /api/ping
              port: 3001
            initialDelaySeconds: 10
            periodSeconds: 3
          imagePullPolicy: Always
      initContainers:
        - name: wait-mongo
          image: busybox
          command: ['sh', '-c', 'until nslookup db-svc; do echo waiting for db-svc; sleep 2; done;']
          envFrom:
            - configMapRef:
                name: apiserver-env-file
        - name: mongo-operator-seed
          image: gitlab.ensimag.fr:5050/sdtd1/projet-sdtd/mongo-operator-seed:test
          env:
            - name: DB_SERVICE
              value: db-svc
          imagePullPolicy: Always
        - name: wait-kafka
          image: busybox
          command: ['sh', '-c', 'until nslookup kafkaa; do echo waiting for kafkaa; sleep 2; done;']
          envFrom:
            - configMapRef:
                name: apiserver-env-file
      imagePullSecrets:
        - name: myregistrykey
